version: '3.8'

services:
  web:
    build: .
    container_name: odp-web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NODE_ENV=production
    volumes:
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
    restart: always

  mobile:
    build: ./mobile
    container_name: odp-mobile
    ports:
      - "5000:80"
    restart: always

networks:
  default:
    name: odp-network
